[tool.poetry]
name = "sqlfluff"
version = "0.1.0"
description = ""
authors = ["TKNGUE <takegue@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlfulff = ">=0.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
